### PR TITLE
Get the updated fee rate before connecting peer

### LINKED ISSUE #603: Channel Open Didn't Complete
Hi, 

I paid 100,000 sats to open a channel.  And something has gone wrong in the process on the Mutiny side.

Payment Hash
5ef51d596ddd10bbc8c6bab0d2de541495426905154f3b658aa743261b14cd22

Payment ID
648dc2524f18fadfd81e9f12

Mutiny Wallet Log
[mutiny-logs.txt](https://github.com/MutinyWallet/mutiny-web/files/11781457/mutiny-logs.txt)

Yesterday it said I had a channel but no liquidity.

This morning it says the channel is closed.

I'm unsure, but could guess, maybe the channel opening hasn't gone well and my funds are being refunded?

Thank you

### PR DESCRIPTION
**Pull request by TonyGiorgio**
Fixes #603

### CODE REVIEW

File: mutiny-core/src/peermanager.rs [hunk 1]
```diff
@@ -321,6 +322,14 @@ pub(crate) async fn connect_peer_if_necessary(
     {
         Ok(())
     } else {
+        // first check to see if the fee rate is mostly up to date
+        // if not, we need to have updated fees or force closures
+        // could occur due to UpdateFee message conflicts.
+        let last_sync = fee_estimator.get_last_sync_time().await;
+        if last_sync.is_none() || utils::now().as_secs() > last_sync.unwrap() + 60 * 10 {
+            fee_estimator.update_fee_estimates().await?;
+        }
```
Comment (benthecarman) [inline mutiny-core/src/peermanager.rs:331]: you do this in 2 different places, could just make this a function on the fee estimator like `update_fee_estimates_if_needed`

**Review by benthecarman — APPROVED** [review]
