### PR TITLE
Better handle syncing transaction from check_address

### LINKED ISSUE #414: `check_address` doesn't work for confirmed addresses?
- If I call `check_address` with a fresh address it returns null.
- If I call it with an address that has been paid I get the tx info I expect.
- But once it's confirmed I get an error: `Failed to conduct chain access operation.`

### PR DESCRIPTION
**Pull request by benthecarman**
Closes #414

When we were try to insert the tx it could can fail if our chain tip isn't caught up, so confirmed txs would fail.

This fixes it so we do it in a spawn_local so it doesn't hold up the api call and will still return correctly even if the sync failed (because the sync is just a small optimization).

Also changed it so if the transaction is confirmed that we properly handle it by either giving bdk the block the tx was included in or if we don't have that, just doing a normal sync so we catch everything correctly.

### CODE REVIEW

File: mutiny-core/src/wallet.rs [hunk 1]
```diff
@@ -87,6 +88,37 @@ impl MutinyWallet {
...
+                // we can insert it directly
+                if let Some(block_id) = block_id {
+                    let mut wallet = self.wallet.try_write()?;
+                    wallet.insert_checkpoint(block_id)?;
+                    wallet.insert_tx(tx, position)?;
+                } else {
+                    // if the transaction is confirmed and we don't have the block id,
+                    // we should just sync the wallet otherwise we can get an error
+                    // with the wallet being behind the blockchain
+                    self.sync().await?
```
Comment (TonyGiorgio) [inline mutiny-core/src/wallet.rs:109]: I'm guessing the `sync()` function then handles the inserts?

And there's no clashing or problems that we are just inserting directly into it's db?

Comment (benthecarman) [reply mutiny-core/src/wallet.rs:109]: > I'm guessing the sync() function then handles the inserts?

Yeah it does.

> And there's no clashing or problems that we are just inserting directly into it's db?

Yeah they do a similar in memory caching thing that we do.

**Review by TonyGiorgio — APPROVED** [review]
