### PR TITLE
Persist failed SpendableOutputs events and retry on startup

### LINKED ISSUE #433: Could not spend spendable outputs panic
This is probably related to a channel closure that I did on this wallet. 

```
INFO mutiny-core/src/logging.rs:27
2023-04-27 20:57:04.786 INFO  [mutiny_core::esplora:220] Starting transaction sync.
[mutiny_wasm.js:2268:17](http://localhost:3420/@fs/data/Dev/Mutiny/mutiny-node/mutiny-wasm/pkg/mutiny_wasm.js)
DEBUG mutiny-core/src/logging.rs:26
2023-04-27 20:57:05.438 DEBUG [lightning::chain::chainmonitor:612] New best block 0000010118f1840b4559ce14ca2ef491e0a734e14b30a852f5de406b237e9217 at height 36878 provided via best_block_updated
[mutiny_wasm.js:2271:17](http://localhost:3420/@fs/data/Dev/Mutiny/mutiny-node/mutiny-wasm/pkg/mutiny_wasm.js)
DEBUG mutiny-core/src/logging.rs:26
2023-04-27 20:57:05.439 DEBUG [lightning::chain::onchaintx:707] Updating claims view at height 36878 with 0 claim requests
[mutiny_wasm.js:2271:17](http://localhost:3420/@fs/data/Dev/Mutiny/mutiny-node/mutiny-wasm/pkg/mutiny_wasm.js)
DEBUG mutiny-core/src/logging.rs:26
2023-04-27 20:57:05.439 DEBUG [lightning::chain::onchaintx:820] Updating claims view at height 36878 with 0 matched transactions in block 36878
[mutiny_wasm.js:2271:17](http://localhost:3420/@fs/data/Dev/Mutiny/mutiny-node/mutiny-wasm/pkg/mutiny_wasm.js)
DEBUG mutiny-core/src/logging.rs:26
2023-04-27 20:57:05.439 DEBUG [lightning::chain::channelmonitor:3244] Descriptor StaticOutput 532ff37cb6c3cb28b5f3ec5f96a0373c1765ab757a7343a40737cd5f50186110:0 marked for spending has got enough confirmations to be passed upstream
[mutiny_wasm.js:2271:17](http://localhost:3420/@fs/data/Dev/Mutiny/mutiny-node/mutiny-wasm/pkg/mutiny_wasm.js)
DEBUG mutiny-core/src/logging.rs:26
2023-04-27 20:57:05.440 DEBUG [lightning::chain::onchaintx:707] Updating claims view at height 36878 with 0 claim requests
[mutiny_wasm.js:2271:17](http://localhost:3420/@fs/data/Dev/Mutiny/mutiny-node/mutiny-wasm/pkg/mutiny_wasm.js)
DEBUG mutiny-core/src/logging.rs:26
2023-04-27 20:57:05.440 DEBUG [lightning::chain::onchaintx:820] Updating claims view at height 36878 with 0 matched transactions in block 36878
[mutiny_wasm.js:2271:17](http://localhost:3420/@fs/data/Dev/Mutiny/mutiny-node/mutiny-wasm/pkg/mutiny_wasm.js)
DEBUG mutiny-core/src/logging.rs:26
2023-04-27 20:57:05.442 DEBUG [event:0] EVENT: SpendableOutputs processing
[mutiny_wasm.js:2271:17](http://localhost:3420/@fs/data/Dev/Mutiny/mutiny-node/mutiny-wasm/pkg/mutiny_wasm.js)
panicked at 'could not spend spendable outputs: ()', /data/Dev/Mutiny/mutiny-node/mutiny-core/src/event.rs:527:22

Stack:

getImports/imports.wbg.__wbg_new_abda76e883ba8a5f/<@http://localhost:3420/@fs/data/Dev/Mutiny/mutiny-node/mutiny-wasm/pkg/mutiny_wasm.js:2129:21
logError@http://localhost:3420/@fs/data/Dev/Mutiny/mutiny-node/mutiny-wasm/pkg/mutiny_wasm.js:232:18
getImports/imports.wbg.__wbg_new_abda76e883ba8a5f@http://localhost:3420/@fs/data/Dev/Mutiny/mutiny-node/mutiny-wasm/pkg/mutiny_wasm.js:2128:66
console_error_panic_hook::Error::new::h41a97964ab0b8763@http://localhost:3420/@fs/data/Dev/Mutiny/mutiny-node/mutiny-wasm/pkg/mutiny_wasm_bg.wasm:wasm-function[56016]:0x1bd0b0e
console_error_panic_hook::hook_impl::hccf120d22d6ba64c@http://localhost:3420/@fs/data/Dev/Mutiny/mutiny-node/mutiny-wasm/pkg/mutiny_wasm_bg.wasm:wasm-function[14472]:0x1553158
console_error_panic_hook::hook::headc4e1f35397d32@http://localhost:3420/@fs/data/Dev/Mutiny/mutiny-node/mutiny-wasm/pkg/mutiny_wasm_bg.…
[mutiny_wasm.js:2123:21](http://localhost:3420/@fs/data/Dev/Mutiny/mutiny-node/mutiny-wasm/pkg/mutiny_wasm.js)
Uncaught (in promise) RuntimeError: unreachable executed
[mutiny_wasm_bg.wasm:29727858:1](http://localhost:3420/@fs/data/Dev/Mutiny/mutiny-node/mutiny-wasm/pkg/mutiny_wasm_bg.wasm)
panicked at 'already borrowed: BorrowMutError', /home/dev/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wasm-bindgen-futures-0.4.33/src/task/singlethread.rs:85:37

Stack:

getImports/imports.wbg.__wbg_new_abda76e883ba8a5f/<@http://localhost:3420/@fs/data/Dev/Mutiny/mutiny-node/mutiny-wasm/pkg/mutiny_wasm.js:2129:21
logError@http://localhost:3420/@fs/data/Dev/Mutiny/mutiny-node/mutiny-wasm/pkg/mutiny_wasm.js:232:18
getImports/imports.wbg.__wbg_new_abda76e883ba8a5f@http://localhost:3420/@fs/data/Dev/Mutiny/mutiny-node/mutiny-wasm/pkg/mutiny_wasm.js:2128:66
console_error_panic_hook::Error::new::h41a97964ab0b8763@http://localhost:3420/@fs/data/Dev/Mutiny/mutiny-node/mutiny-wasm/pkg/mutiny_wasm_bg.wasm:wasm-function[56016]:0x1bd0b0e
console_error_panic_hook::hook_impl::hccf120d22d6ba64c@http://localhost:3420/@fs/data/Dev/Mutiny/mutiny-node/mutiny-wasm/pkg/mutiny_wasm_bg.wasm:wasm-function[14472]:0x1553158
console_error_panic_hook::hook::headc4e1f35397d32@http://localhost:3420/@fs/dat…
[mutiny_wasm.js:2123:21](http://localhost:3420/@fs/data/Dev/Mutiny/mutiny-node/mutiny-wasm/pkg/mutiny_wasm.js)
Uncaught (in promise) RuntimeError: unreachable executed
[mutiny_wasm_bg.wasm:25756811:1](http://localhost:3420/@fs/data/Dev/Mutiny/mutiny-node/mutiny-wasm/pkg/mutiny_wasm_bg.wasm)
INFO mutiny-core/src/logging.rs:27
2023-04-27 20:57:05.535 INFO  [mutiny_core::esplora:316] Finished transaction sync.
```

Afterwards, here's a few logs that might be relevant. It does seem like I did get all the funds on chain, so perhaps not a big worry as far as the funds go.

```
INFO mutiny-core/src/logging.rs:27
2023-04-27 20:58:04.908 INFO  [mutiny_core::esplora:220] Starting transaction sync.
[mutiny_wasm.js:2268:17](http://localhost:3420/@fs/data/Dev/Mutiny/mutiny-node/mutiny-wasm/pkg/mutiny_wasm.js)
DEBUG mutiny-core/src/logging.rs:26
2023-04-27 20:58:05.346 DEBUG [lightning::chain::chainmonitor:612] New best block 000001a5755469dd348a12d71f2f4a1eec11f08dcf32633f872dcf4036b8db92 at height 36879 provided via best_block_updated
[mutiny_wasm.js:2271:17](http://localhost:3420/@fs/data/Dev/Mutiny/mutiny-node/mutiny-wasm/pkg/mutiny_wasm.js)
DEBUG mutiny-core/src/logging.rs:26
2023-04-27 20:58:05.347 DEBUG [lightning::chain::onchaintx:707] Updating claims view at height 36879 with 0 claim requests
[mutiny_wasm.js:2271:17](http://localhost:3420/@fs/data/Dev/Mutiny/mutiny-node/mutiny-wasm/pkg/mutiny_wasm.js)
DEBUG mutiny-core/src/logging.rs:26
2023-04-27 20:58:05.348 DEBUG [lightning::chain::onchaintx:820] Updating claims view at height 36879 with 0 matched transactions in block 36879
[mutiny_wasm.js:2271:17](http://localhost:3420/@fs/data/Dev/Mutiny/mutiny-node/mutiny-wasm/pkg/mutiny_wasm.js)
DEBUG mutiny-core/src/logging.rs:26
2023-04-27 20:58:05.349 DEBUG [lightning::chain::onchaintx:707] Updating claims view at height 36879 with 0 claim requests
[mutiny_wasm.js:2271:17](http://localhost:3420/@fs/data/Dev/Mutiny/mutiny-node/mutiny-wasm/pkg/mutiny_wasm.js)
DEBUG mutiny-core/src/logging.rs:26
2023-04-27 20:58:05.349 DEBUG [lightning::chain::onchaintx:820] Updating claims view at height 36879 with 0 matched transactions in block 36879
[mutiny_wasm.js:2271:17](http://localhost:3420/@fs/data/Dev/Mutiny/mutiny-node/mutiny-wasm/pkg/mutiny_wasm.js)
INFO mutiny-core/src/logging.rs:27
2023-04-27 20:58:05.431 INFO  [mutiny_core::esplora:316] Finished transaction sync.
```

```
INFO mutiny-core/src/logging.rs:27
2023-04-27 20:59:04.738 INFO  [mutiny_core::esplora:220] Starting transaction sync.
[mutiny_wasm.js:2268:17](http://localhost:3420/@fs/data/Dev/Mutiny/mutiny-node/mutiny-wasm/pkg/mutiny_wasm.js)
DEBUG mutiny-core/src/logging.rs:26
2023-04-27 20:59:05.214 DEBUG [lightning::chain::chainmonitor:612] New best block 0000009a7c28c28ac3292d063870ff68bbb051771559303a657e7f5bbcbb9c3d at height 36881 provided via best_block_updated
[mutiny_wasm.js:2271:17](http://localhost:3420/@fs/data/Dev/Mutiny/mutiny-node/mutiny-wasm/pkg/mutiny_wasm.js)
DEBUG mutiny-core/src/logging.rs:26
2023-04-27 20:59:05.214 DEBUG [lightning::chain::onchaintx:707] Updating claims view at height 36881 with 0 claim requests
[mutiny_wasm.js:2271:17](http://localhost:3420/@fs/data/Dev/Mutiny/mutiny-node/mutiny-wasm/pkg/mutiny_wasm.js)
DEBUG mutiny-core/src/logging.rs:26
2023-04-27 20:59:05.214 DEBUG [lightning::chain::onchaintx:820] Updating claims view at height 36881 with 0 matched transactions in block 36881
[mutiny_wasm.js:2271:17](http://localhost:3420/@fs/data/Dev/Mutiny/mutiny-node/mutiny-wasm/pkg/mutiny_wasm.js)
DEBUG mutiny-core/src/logging.rs:26
2023-04-27 20:59:05.216 DEBUG [lightning::chain::onchaintx:707] Updating claims view at height 36881 with 0 claim requests
[mutiny_wasm.js:2271:17](http://localhost:3420/@fs/data/Dev/Mutiny/mutiny-node/mutiny-wasm/pkg/mutiny_wasm.js)
DEBUG mutiny-core/src/logging.rs:26
2023-04-27 20:59:05.216 DEBUG [lightning::chain::onchaintx:820] Updating claims view at height 36881 with 0 matched transactions in block 36881
[mutiny_wasm.js:2271:17](http://localhost:3420/@fs/data/Dev/Mutiny/mutiny-node/mutiny-wasm/pkg/mutiny_wasm.js)
INFO mutiny-core/src/logging.rs:27
2023-04-27 20:59:05.309 INFO  [mutiny_core::esplora:316] Finished transaction sync.
```

```
INFO mutiny-core/src/logging.rs:27
2023-04-27 21:00:04.922 INFO  [mutiny_core::esplora:220] Starting transaction sync.
[mutiny_wasm.js:2268:17](http://localhost:3420/@fs/data/Dev/Mutiny/mutiny-node/mutiny-wasm/pkg/mutiny_wasm.js)
DEBUG mutiny-core/src/logging.rs:26
2023-04-27 21:00:05.291 DEBUG [lightning::chain::chainmonitor:612] New best block 00000174cd1bab49d854a7a79fc024e485a18ae59d0c9ebd3b1aad94e578c509 at height 36883 provided via best_block_updated
[mutiny_wasm.js:2271:17](http://localhost:3420/@fs/data/Dev/Mutiny/mutiny-node/mutiny-wasm/pkg/mutiny_wasm.js)
DEBUG mutiny-core/src/logging.rs:26
2023-04-27 21:00:05.291 DEBUG [lightning::chain::onchaintx:707] Updating claims view at height 36883 with 0 claim requests
[mutiny_wasm.js:2271:17](http://localhost:3420/@fs/data/Dev/Mutiny/mutiny-node/mutiny-wasm/pkg/mutiny_wasm.js)
DEBUG mutiny-core/src/logging.rs:26
2023-04-27 21:00:05.292 DEBUG [lightning::chain::onchaintx:820] Updating claims view at height 36883 with 0 matched transactions in block 36883
[mutiny_wasm.js:2271:17](http://localhost:3420/@fs/data/Dev/Mutiny/mutiny-node/mutiny-wasm/pkg/mutiny_wasm.js)
DEBUG mutiny-core/src/logging.rs:26
2023-04-27 21:00:05.293 DEBUG [lightning::chain::onchaintx:707] Updating claims view at height 36883 with 0 claim requests
[mutiny_wasm.js:2271:17](http://localhost:3420/@fs/data/Dev/Mutiny/mutiny-node/mutiny-wasm/pkg/mutiny_wasm.js)
DEBUG mutiny-core/src/logging.rs:26
2023-04-27 21:00:05.293 DEBUG [lightning::chain::onchaintx:820] Updating claims view at height 36883 with 0 matched transactions in block 36883
[mutiny_wasm.js:2271:17](http://localhost:3420/@fs/data/Dev/Mutiny/mutiny-node/mutiny-wasm/pkg/mutiny_wasm.js)
INFO mutiny-core/src/logging.rs:27
2023-04-27 21:00:05.367 INFO  [mutiny_core::esplora:316] Finished transaction sync.
[mutiny_wasm.js:2268:17](http://localhost:3420/@fs/data/Dev/Mutiny/mutiny-node/mutiny-wasm/pkg/mutiny_wasm.js)
```

and it just keeps going like that forever. Keeps updating claims view.

### PR DESCRIPTION
**Pull request by benthecarman**
Closes #433

This should be best for failed spendable outputs, if we mess up and or miss any we will persist and retry later. This also will let us fix things if they fail with updates because they will be saved to storage.

### CODE REVIEW

File: mutiny-core/src/ldkstorage.rs [hunk 1]
```diff
@@ -262,6 +266,64 @@ impl MutinyNodePersister {
...
+    /// This is used to retry spending them later.
+    pub fn persist_failed_spendable_outputs(
+        &self,
+        failed: Vec<SpendableOutputDescriptor>,
+    ) -> anyhow::Result<()> {
+        let key = self.get_key(FAILED_SPENDABLE_OUTPUT_DESCRIPTOR_KEY);
+
+        // get the currently stored descriptors encoded as hex
+        // if there are none, use an empty vector
+        let mut descriptors: Vec<String> = self.storage.get(&key)?.unwrap_or_default();
```
Comment (TonyGiorgio) [inline mutiny-core/src/ldkstorage.rs:282]: If there is a storage reading problem but there are outputs in there, won't that overwrite? Shouldn't it only trigger this if it's `None`, but not a key reading error?

Comment (benthecarman) [reply mutiny-core/src/ldkstorage.rs:282]: If it errors or is `None` it will return an empty vector and the retry logic is skipped.

Comment (TonyGiorgio) [reply mutiny-core/src/ldkstorage.rs:282]: But this is the persist logic part where it could be overwritten with an empty vec + the new descriptor

Comment (benthecarman) [reply mutiny-core/src/ldkstorage.rs:282]: this is calling `get_failed_spendable_outputs`

Comment (TonyGiorgio) [reply mutiny-core/src/ldkstorage.rs:282]: it calls `get` on `storage` and that returns `Result<Option<T>, MutinyError>` and so `unwrap_or_default` will execute the `unwrap` case on both `MutinyError` and `None`, right?

Comment (benthecarman) [reply mutiny-core/src/ldkstorage.rs:282]: I do `self.storage.get(&key)?.unwrap_or_default();` so the `?` will propgate the error up and fail this function, the `unwrap_or_default` will turn create an empty vec if it is None. So if there is any errors it will be properly handled, the `unwrap_or_default` is only handling if there is no stored failed spendable outputs

Comment (TonyGiorgio) [reply mutiny-core/src/ldkstorage.rs:282]: Ahh, I see. Yeah that makes sense thansk for clarifying.

**Review by TonyGiorgio — APPROVED** [review]
