### PR TITLE
Retry wallet lock for syncing on-chain wallet

### LINKED ISSUE #593: Could not get wallet lock: try_lock failed because the operation would block
This comes from: https://github.com/MutinyWallet/mutiny-web/issues/249

For a few invoices in a row this error kept repeating. I don't think a restart happened so that might have fixed it, but not sure if something is just holding the lock forever or what. Full logs are there. 

```
2023-06-15 02:15:59.985 INFO  [mutiny_core::esplora:220] Starting transaction sync.
2023-06-15 02:16:00.164 INFO  [mutiny_core::esplora:316] Finished transaction sync.
2023-06-15 02:16:00.242 TRACE [mutiny_core::networking::socket:77] received binary data from websocket
2023-06-15 02:16:00.242 TRACE [lightning::ln::peer_handler:1381] Received message Pong(Pong { byteslen: 0 }) from 03aefa43fbb4009b21a4129d05953974b7dbabbbfb511921410080860fca8ee1f0
2023-06-15 02:16:06.554 TRACE [lightning_invoice::utils:465] Creating invoice with payment hash ae903303dc379b0b0ee1dbb4496f9dda97e8dce0eb73b87d43bd400e1e2d1389
2023-06-15 02:16:06.554 TRACE [lightning_invoice::utils:529] Considering 2 channels for invoice route hints
2023-06-15 02:16:06.554 TRACE [lightning_invoice::utils:553] Channel with enough inbound capacity exists for invoice route hints
2023-06-15 02:16:06.554 TRACE [lightning_invoice::utils:563] Channel with connected peer exists for invoice route hints
2023-06-15 02:16:06.554 TRACE [lightning_invoice::utils:588] Preferring counterparty 03aefa43fbb4009b21a4129d05953974b7dbabbbfb511921410080860fca8ee1f0 channel b3ceb5aaaf747f52b50d7d922ee4bd7a698661c6a971ea5fed245f735cd7d5e2 (SCID Some(873410255762685952), 202394262 msats) over 1d079fff8394e7cf6083bb96d2c4d9a94a9958c42e100a4d4fd75450285c586f (SCID Some(873412454846562305), 0 msats) for invoice route hints
2023-06-15 02:16:06.555 TRACE [lightning_invoice::utils:644] Including channel b3ceb5aaaf747f52b50d7d922ee4bd7a698661c6a971ea5fed245f735cd7d5e2 in invoice route hints
2023-06-15 02:16:06.568 INFO  [mutiny_core::node:735] SUCCESS: generated invoice: lnbc999990n1pjg5arxdqqnp4qvk6gxmj7y82lpaf9sdptp54yd3smwxeyl2hnaxlsljprt3ra0sfkpp546grxq7ux7dskrhpmw6yjmuam2t73h8qademsl2rh4qqu83dzwyssp5cmm4eeydq65jhvans6gck7uxecsz384v35dae9qe2pl507f7y2us9qyysgqcqzptxqrpwurzjqwh05slmksqfkgdyz2wst9fewjmah2amldg3jg2pqzqgvr723mslpyw5pnmhgevfauqqqqlgqqqqqzsqyg0p7l7zaet5kw4yhuznhxmrntw7ns9w8h73lr0sv6z9f5386v0qu3u4ktg9kuejk4sme2z50lfckf570cey9eh8ul43k7ug0psja0rjqpsn7rpv
2023-06-15 02:16:09.942 TRACE [mutiny_core::background:575] Calling PeerManager's timer_tick_occurred
2023-06-15 02:16:09.942 TRACE [lightning::ln::peer_handler:1071] Enqueueing message Ping { ponglen: 0, byteslen: 64 } to 03aefa43fbb4009b21a4129d05953974b7dbabbbfb511921410080860fca8ee1f0
2023-06-15 02:16:09.942 TRACE [mutiny_core::networking::proxy:92] sent data down websocket
2023-06-15 02:16:10.403 TRACE [mutiny_core::networking::socket:77] received binary data from websocket
2023-06-15 02:16:10.403 TRACE [lightning::ln::peer_handler:1381] Received message Pong(Pong { byteslen: 0 }) from 03aefa43fbb4009b21a4129d05953974b7dbabbbfb511921410080860fca8ee1f0
2023-06-15 02:16:10.430 ERROR [mutiny_core::onchain:123] Could not get wallet lock: try_lock failed because the operation would block
2023-06-15 02:16:10.430 INFO  [mutiny_core::nodemanager:1179] We are synced!
```

### PR DESCRIPTION
**Pull request by benthecarman**
Closes #593

### CODE REVIEW

File: mutiny-core/src/onchain.rs [hunk 1]
```diff
@@ -115,19 +120,29 @@ impl<S: MutinyStorage> OnChainWallet<S> {
             .await?;
 
         // get new wallet lock for writing and apply the update
-        match self.wallet.try_write() {
-            Ok(mut wallet) => match wallet.apply_update(update) {
-                Ok(_) => wallet.commit()?,
+        loop {
+            match self.wallet.try_write() {
+                Ok(mut wallet) => match wallet.apply_update(update.clone()) {
```
Comment (TonyGiorgio) [inline mutiny-core/src/onchain.rs:125]: Instead of cloning update, you could make the `Ok(_) => wallet.commit()?` condition:

```
                    Ok(_) => {
                        wallet.commit()?;
                        return Ok(());
                    }
```

File: mutiny-core/src/onchain.rs [hunk 2]
```diff
@@ -115,19 +120,29 @@ impl<S: MutinyStorage> OnChainWallet<S> {
             .await?;
 
         // get new wallet lock for writing and apply the update
-        match self.wallet.try_write() {
-            Ok(mut wallet) => match wallet.apply_update(update) {
-                Ok(_) => wallet.commit()?,
+        loop {
```
Comment (TonyGiorgio) [inline mutiny-core/src/onchain.rs:123]: Should it loop forever? What about just doing a `for _ in 1..3` with a 1s sleep or something?

Comment (benthecarman) [reply mutiny-core/src/onchain.rs]: changed to 10 iterations with 250ms sleep

File: mutiny-core/src/onchain.rs (hunk 1 above)
Comment (benthecarman) [reply mutiny-core/src/onchain.rs]: good idea

**Review by TonyGiorgio — COMMENTED** [review]
Awesome. Last thing, in nodemanager.rs, should we change this: 

```
                if let Err(e) = nm.sync().await {
                    log_error!(nm.logger, "Failed to sync: {e}");
                }

                // if this is the first sync, set the done_first_sync flag
                if !synced {
                    let _ = nm.storage.set_done_first_sync();
                    synced = true;
                }
```

And if error then synced does not equal true?

**Comment by benthecarman** [comment]
> Awesome. Last thing, in nodemanager.rs, should we change this:
> 
> ```
>                 if let Err(e) = nm.sync().await {
>                     log_error!(nm.logger, "Failed to sync: {e}");
>                 }
> 
>                 // if this is the first sync, set the done_first_sync flag
>                 if !synced {
>                     let _ = nm.storage.set_done_first_sync();
>                     synced = true;
>                 }
> ```
> 
> And if error then synced does not equal true?

did it with the else if statement

**Review by TonyGiorgio — APPROVED** [review]
